### ISSUE TITLE
Cpu usage

### ISSUE THREAD

**Issue by Brajesh3** [brahmkshatriya/echo#26]
### Summary

Same as title

### Reproduction Steps

Start playing songs
Go to sleep
When you wake up
You see cpu overuse notification from system every morning 

### Expected Result

The application or process should manage system resources efficiently without causing excessive CPU usage. The CPU usage should remain within normal operational limits.

### Actual Result

The CPU usage spikes to 17.1%, resulting in high battery usage, requiring manual termination of the app or process 
![Screenshot_20240905-081250_Device care](https://github.com/user-attachments/assets/015d2368-ab18-425f-bf11-d2addda9a314)

### Device Information

Echo version: 1.0.0-a82109c
Brand: samsung m11
Arch: arm32
Android version: 12

### Checklist

- [x] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Try again, with the new versions, is it still that taking that much cpu?

**Comment by Brajesh3** [comment]
now that i think about it,
i have not received any cpu overuse notification from system.

**Comment by brahmkshatriya** [comment]
I think the most likely cause of cpu consumption was using
`FilterMediaSource`, which probably checked and tried to filter out video content from an audio only file, which probably caused alot of cpu usage. I've removed it now, so if any extension now gives out video content in an `Streamable.Audio`, it would still work.
