### ISSUE TITLE
Post nightly releases here

### ISSUE THREAD

**Issue by Ahmetto7** [brahmkshatriya/echo#48]
### Summary

Post versions here

### The Problem

You can publish nightly versions here or reopen the discord channel (btwnot everyone uses telegram)

### The Ideal Solution

Release versions

**Comment by brahmkshatriya** [comment]
https://discord.com/channels/1208756142474399764/1208770458032279613

**Comment by Ahmetto7** [comment]
The link does not work

**Comment by brahmkshatriya** [comment]
https://discord.gg/J3WvbBUU8Z

**Comment by Bhardwaj10Ankit** [comment]
@brahmkshatriya yaar, I'm aware about the discord/telegram channels.... I was just thinking about nightly release over GitHub, Just like [Lawnchair](https://github.com/LawnchairLauncher/lawnchair/releases) and others do, have a look.

**Comment by Ahmetto7** [comment]
Actually, the application has been under development for a long time and I wonder why it hasn't been released yet.
